applications:
  test-namespace:
    guestbook:
      enabled: true
      chartRepo: https://cloudnativeapp.github.io/charts/curated
      chartName: guestbook
      chartVersion: 0.2.0
      valuesRevision: HEAD