{{- $metadata := .Values.metadata }}
{{- range $namespace, $namespaceValue := .Values.applications }}
{{- range $key, $value := $namespaceValue }}
{{- if $value.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}-{{ $metadata.clusterName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: {{ $key }}
    cloud: {{ $metadata.cloud | quote }}
    cluster-name: {{ $metadata.clusterName | quote }}
    account-id: {{ $metadata.accountId | quote }}
    region: {{ $metadata.region | quote }}
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
      repoURL: 'https://github.com/JacobAmar/argocd-applicationset-test'
      targetRevision: {{ $value.valuesRevision }}
      path: apps/{{$key}}
      plugin:
        name: helm-gomplate
        env:
        - name: CHART_NAME
          value: {{ $value.chartName  }}
        - name: CHART_REPO
          value: {{ $value.chartRepo  }}
        - name: CHART_VERSION
          value: {{ $value.chartVersion  }}
        - name: CHART_PATH
          value: 'apps/{{$key}}'
        - name: CLUSTER_VALUES_FILE
          value: '$values/app-of-apps/{{$metadata.cloud}}/{{ $metadata.accountId }}/{{$metadata.region }}/{{$metadata.clusterName}}.yaml'
        - name: VALUE_FILES
          value: '-f $values/apps/{{$key}}/values.yaml -f $values/apps/{{$key}}/{{$metadata.clusterName}}.yaml'
  
  destination:
    server: {{ $metadata.server | default "https://kubernetes.default.svc" }}
    namespace: {{ $namespace }}
  
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
    - Replace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10s

  revisionHistoryLimit: 2
{{- end }}
{{- end }}
{{- end }}