repoServer:
  extraContainers:
  - name: gomplate-helm
    image: pltsciart/helm-gomplate:latest
    command: ["sh", "-c", "sleep infinity"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins

configs:
  cmp:
    create: true
    plugins:
     gomplate-helm:
       generate:
        command: ["sh", "-c"]
        args:
          - |
            gomplate -c .=../../$CLUSTER_VALUES_FILE -f values.gotmpl.yaml -o values.yaml | helm template . $VALUE_FILES